# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ciurkoj/Documents/6004CEM/Parallel_Element

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ciurkoj/Documents/6004CEM/Parallel_Element

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ciurkoj/Documents/6004CEM/Parallel_Element/CMakeFiles /home/ciurkoj/Documents/6004CEM/Parallel_Element/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ciurkoj/Documents/6004CEM/Parallel_Element/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Parallel

# Build rule for target.
Parallel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Parallel
.PHONY : Parallel

# fast build rule for target.
Parallel/fast:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/build
.PHONY : Parallel/fast

SourceFiles/Particle.o: SourceFiles/Particle.cpp.o

.PHONY : SourceFiles/Particle.o

# target to build an object file
SourceFiles/Particle.cpp.o:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/Particle.cpp.o
.PHONY : SourceFiles/Particle.cpp.o

SourceFiles/Particle.i: SourceFiles/Particle.cpp.i

.PHONY : SourceFiles/Particle.i

# target to preprocess a source file
SourceFiles/Particle.cpp.i:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/Particle.cpp.i
.PHONY : SourceFiles/Particle.cpp.i

SourceFiles/Particle.s: SourceFiles/Particle.cpp.s

.PHONY : SourceFiles/Particle.s

# target to generate assembly for a file
SourceFiles/Particle.cpp.s:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/Particle.cpp.s
.PHONY : SourceFiles/Particle.cpp.s

SourceFiles/Position.o: SourceFiles/Position.cpp.o

.PHONY : SourceFiles/Position.o

# target to build an object file
SourceFiles/Position.cpp.o:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/Position.cpp.o
.PHONY : SourceFiles/Position.cpp.o

SourceFiles/Position.i: SourceFiles/Position.cpp.i

.PHONY : SourceFiles/Position.i

# target to preprocess a source file
SourceFiles/Position.cpp.i:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/Position.cpp.i
.PHONY : SourceFiles/Position.cpp.i

SourceFiles/Position.s: SourceFiles/Position.cpp.s

.PHONY : SourceFiles/Position.s

# target to generate assembly for a file
SourceFiles/Position.cpp.s:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/Position.cpp.s
.PHONY : SourceFiles/Position.cpp.s

SourceFiles/ScheduleType.o: SourceFiles/ScheduleType.cpp.o

.PHONY : SourceFiles/ScheduleType.o

# target to build an object file
SourceFiles/ScheduleType.cpp.o:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/ScheduleType.cpp.o
.PHONY : SourceFiles/ScheduleType.cpp.o

SourceFiles/ScheduleType.i: SourceFiles/ScheduleType.cpp.i

.PHONY : SourceFiles/ScheduleType.i

# target to preprocess a source file
SourceFiles/ScheduleType.cpp.i:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/ScheduleType.cpp.i
.PHONY : SourceFiles/ScheduleType.cpp.i

SourceFiles/ScheduleType.s: SourceFiles/ScheduleType.cpp.s

.PHONY : SourceFiles/ScheduleType.s

# target to generate assembly for a file
SourceFiles/ScheduleType.cpp.s:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/ScheduleType.cpp.s
.PHONY : SourceFiles/ScheduleType.cpp.s

SourceFiles/main.o: SourceFiles/main.cpp.o

.PHONY : SourceFiles/main.o

# target to build an object file
SourceFiles/main.cpp.o:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/main.cpp.o
.PHONY : SourceFiles/main.cpp.o

SourceFiles/main.i: SourceFiles/main.cpp.i

.PHONY : SourceFiles/main.i

# target to preprocess a source file
SourceFiles/main.cpp.i:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/main.cpp.i
.PHONY : SourceFiles/main.cpp.i

SourceFiles/main.s: SourceFiles/main.cpp.s

.PHONY : SourceFiles/main.s

# target to generate assembly for a file
SourceFiles/main.cpp.s:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/main.cpp.s
.PHONY : SourceFiles/main.cpp.s

SourceFiles/particleManipulation.o: SourceFiles/particleManipulation.cpp.o

.PHONY : SourceFiles/particleManipulation.o

# target to build an object file
SourceFiles/particleManipulation.cpp.o:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/particleManipulation.cpp.o
.PHONY : SourceFiles/particleManipulation.cpp.o

SourceFiles/particleManipulation.i: SourceFiles/particleManipulation.cpp.i

.PHONY : SourceFiles/particleManipulation.i

# target to preprocess a source file
SourceFiles/particleManipulation.cpp.i:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/particleManipulation.cpp.i
.PHONY : SourceFiles/particleManipulation.cpp.i

SourceFiles/particleManipulation.s: SourceFiles/particleManipulation.cpp.s

.PHONY : SourceFiles/particleManipulation.s

# target to generate assembly for a file
SourceFiles/particleManipulation.cpp.s:
	$(MAKE) -f CMakeFiles/Parallel.dir/build.make CMakeFiles/Parallel.dir/SourceFiles/particleManipulation.cpp.s
.PHONY : SourceFiles/particleManipulation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Parallel"
	@echo "... SourceFiles/Particle.o"
	@echo "... SourceFiles/Particle.i"
	@echo "... SourceFiles/Particle.s"
	@echo "... SourceFiles/Position.o"
	@echo "... SourceFiles/Position.i"
	@echo "... SourceFiles/Position.s"
	@echo "... SourceFiles/ScheduleType.o"
	@echo "... SourceFiles/ScheduleType.i"
	@echo "... SourceFiles/ScheduleType.s"
	@echo "... SourceFiles/main.o"
	@echo "... SourceFiles/main.i"
	@echo "... SourceFiles/main.s"
	@echo "... SourceFiles/particleManipulation.o"
	@echo "... SourceFiles/particleManipulation.i"
	@echo "... SourceFiles/particleManipulation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

